webtalk_init -webtalk_dir /home/linkuri267/cnn/cnn.sim/sim_1/behav/xsim/xsim.dir/conv_layer_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 28 23:32:51 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "94345d9be63e57af92027842ce62833f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "74d96538fcc34a769a4d210eceedae6b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "156" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2700.443 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "130152_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3107451720 -regid "" -xml /home/linkuri267/cnn/cnn.sim/sim_1/behav/xsim/xsim.dir/conv_layer_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/linkuri267/cnn/cnn.sim/sim_1/behav/xsim/xsim.dir/conv_layer_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/linkuri267/cnn/cnn.sim/sim_1/behav/xsim/xsim.dir/conv_layer_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
