

`define DATA_WIDTH 32
`define KERNEL_SIZE 3
`define SOURCE_SIZE 99
//`define DESTINATION_SIZE `SOURCE_SIZE-`KERNEL_SIZE+1
`define DESTINATION_SIZE 97
`define POOLING_FACTOR 3
`define POOLED_IMAGE_SIZE `DESTINATION_SIZE/`POOLING_FACTOR + 1 //assuming not divisible
//`define POOLED_IMAGE_SIZE = `DESTINATION_SIZE/`POOLING_FACTOR //assuming divisible
`define ROW_COUNTER_SIZE $clog2(`POOLING_FACTOR)